version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: tnews-server
    ports:
      - "3000:3000"
    volumes:
      - ./users.json:/app/users.json
      - ./posts.json:/app/posts.json
      - ./public/uploads:/app/public/uploads
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/users.json"]
      interval: 5s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tnews-frontend
    ports:
      - "5173:5173"
    depends_on:
      server:
        condition: service_healthy
    environment:
      - VITE_BACKEND_URL=http://server:3000